-- TABLAS

CREATE TABLE roles (
    id_rol        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(50)  NOT NULL UNIQUE,
    descripcion   VARCHAR2(150) NOT NULL
);

CREATE TABLE usuarios (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol          NUMBER       NOT NULL,
    nombre_completo VARCHAR2(120) NOT NULL,
    email           VARCHAR2(120) NOT NULL UNIQUE,
    password_hash   VARCHAR2(255) NOT NULL,
    telefono        VARCHAR2(20),
    fecha_registro  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    estado          VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
    CONSTRAINT chk_usuarios_estado CHECK (estado IN ('ACTIVO','INACTIVO')),
    CONSTRAINT fk_usuarios_roles
        FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
);

CREATE TABLE pacientes (
    id_paciente       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER       NOT NULL UNIQUE,
    fecha_nacimiento  DATE,
    sexo              VARCHAR2(10) DEFAULT 'Otro',
    provincia         VARCHAR2(80),
    canton            VARCHAR2(80),
    direccion_detalle VARCHAR2(180),
    estatura_cm       NUMBER(5,2),
    peso_kg           NUMBER(5,2),
    CONSTRAINT chk_pacientes_sexo CHECK (sexo IN ('Mujer','Hombre','Otro')),
    CONSTRAINT fk_pacientes_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE TABLE historiales_medicos (
    id_historial          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente           NUMBER      NOT NULL UNIQUE,
    actividad_fisica      VARCHAR2(120),
    cuidado_piel          VARCHAR2(180),
    usa_cremas_comerciales NUMBER(1) DEFAULT 0,
    consumo_agua_litros   NUMBER(4,2),
    evaluacion_facial     VARCHAR2(180),
    observaciones         CLOB,
    fecha_actualizacion   TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_historial_paciente
        FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);

CREATE TABLE categorias_tratamientos (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(80)  NOT NULL UNIQUE,
    descripcion  VARCHAR2(180) NOT NULL
);

CREATE TABLE tratamientos (
    id_tratamiento   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria     NUMBER      NOT NULL,
    nombre           VARCHAR2(120) NOT NULL UNIQUE,
    descripcion      CLOB         NOT NULL,
    precio_referencia NUMBER(10,2) NOT NULL,
    duracion_minutos NUMBER(4)     NOT NULL,
    activo           NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT fk_tratamientos_categoria
        FOREIGN KEY (id_categoria) REFERENCES categorias_tratamientos(id_categoria)
);

CREATE TABLE tratamiento_imagenes (
    id_imagen     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tratamiento NUMBER      NOT NULL,
    titulo        VARCHAR2(120) NOT NULL,
    ruta_archivo  VARCHAR2(180) NOT NULL,
    orden_visual  NUMBER(3)     DEFAULT 1 NOT NULL,
    CONSTRAINT fk_imagenes_tratamiento
        FOREIGN KEY (id_tratamiento) REFERENCES tratamientos(id_tratamiento)
);

CREATE TABLE tratamiento_parametros (
    id_parametro   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tratamiento NUMBER      NOT NULL,
    nombre_parametro VARCHAR2(80) NOT NULL,
    valor_parametro  VARCHAR2(80) NOT NULL,
    unidad           VARCHAR2(30),
    CONSTRAINT fk_parametros_tratamiento
        FOREIGN KEY (id_tratamiento) REFERENCES tratamientos(id_tratamiento)
);

CREATE TABLE citas (
    id_cita        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente    NUMBER      NOT NULL,
    id_tratamiento NUMBER      NOT NULL,
    fecha_hora     TIMESTAMP   NOT NULL,
    estado         VARCHAR2(12) DEFAULT 'SOLICITADA' NOT NULL,
    motivo         VARCHAR2(180),
    notas          CLOB,
    fecha_creacion TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_citas_estado CHECK (estado IN ('SOLICITADA','CONFIRMADA','ATENDIDA','CANCELADA')),
    CONSTRAINT fk_citas_paciente
        FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    CONSTRAINT fk_citas_tratamiento
        FOREIGN KEY (id_tratamiento) REFERENCES tratamientos(id_tratamiento)
);

CREATE TABLE mensajes_contacto (
    id_mensaje   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(120) NOT NULL,
    email        VARCHAR2(120) NOT NULL,
    telefono     VARCHAR2(20),
    asunto       VARCHAR2(120) NOT NULL,
    mensaje      CLOB          NOT NULL,
    fecha_envio  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    atendido     NUMBER(1)     DEFAULT 0 NOT NULL
);

CREATE TABLE comentarios_tratamientos (
    id_comentario    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tratamiento   NUMBER      NOT NULL,
    id_paciente      NUMBER,
    calificacion     NUMBER(1),
    comentario       CLOB        NOT NULL,
    fecha_comentario TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_comentarios_calificacion CHECK (calificacion BETWEEN 1 AND 5),
    CONSTRAINT fk_comentarios_tratamiento
        FOREIGN KEY (id_tratamiento) REFERENCES tratamientos(id_tratamiento),
    CONSTRAINT fk_comentarios_paciente
        FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);

-- DATOS DE INICIO

INSERT INTO roles (nombre, descripcion) VALUES
('ADMINISTRADOR', 'Gestiona el contenido y las citas de la clínica');

INSERT INTO roles (nombre, descripcion) VALUES
('PACIENTE', 'Usuario final que solicita información y reserva tratamientos');

INSERT INTO usuarios (id_rol, nombre_completo, email, password_hash, telefono) VALUES
(1, 'Dr. Roberto Vargas Rojas', 'drrobertovargasrojas@gmail.com', 'Admin1234', '8756-0542');

INSERT INTO usuarios (id_rol, nombre_completo, email, password_hash, telefono) VALUES
(2, 'Ana Vargas', 'ana@gmail.com', 'Paciente123', '8888-1111');

INSERT INTO pacientes (id_usuario, fecha_nacimiento, sexo, provincia, canton, direccion_detalle, estatura_cm, peso_kg) VALUES
(2, DATE '1991-03-21', 'Mujer', 'Alajuela', 'Palmares', 'Palmares centro', 152.00, 53.00);

INSERT INTO historiales_medicos (id_paciente, actividad_fisica, cuidado_piel, usa_cremas_comerciales, consumo_agua_litros, evaluacion_facial, observaciones) VALUES
(1, 'Yoga 2 veces por semana', 'Uso diario de protector solar', 1, 1.50, 'Fototipo III, piel mixta, leve bronceado', 'Paciente apta para valoración estética inicial.');

INSERT INTO categorias_tratamientos (nombre, descripcion) VALUES
('Facial', 'Tratamientos enfocados en armonización, revitalización y glow facial');

INSERT INTO categorias_tratamientos (nombre, descripcion) VALUES
('Capilar', 'Procedimientos para fortalecer salud folicular y cuero cabelludo');

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(1, 'Botox', 'Aplicación de toxina botulínica para líneas de expresión.', 60.00, 30, 1);

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(1, 'Mesoterapia Facial', 'Revitalización facial con principios activos.', 45000.00, 45, 1);

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(2, 'Mesoterapia Capilar', 'Fortalecimiento del folículo y salud capilar.', 50000.00, 60, 1);

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(1, 'Relleno de Labios', 'Armonización y volumen labial personalizado.', 75000.00, 50, 1);

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(1, 'BB Lips', 'Pigmentación e hidratación labial estética.', 38000.00, 60, 1);

INSERT INTO tratamientos (id_categoria, nombre, descripcion, precio_referencia, duracion_minutos, activo) VALUES
(1, 'Mesobótox', 'Combinación de glow, textura uniforme y suavizado.', 55000.00, 45, 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(1, 'Botox principal', 'assets/img/treatments/botox.jpeg', 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(2, 'Mesoterapia facial', 'assets/img/treatments/mesoterapia-facial.jpeg', 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(3, 'Mesoterapia capilar', 'assets/img/treatments/mesoterapia-capilar.jpeg', 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(4, 'Relleno de labios', 'assets/img/treatments/relleno-labios.jpeg', 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(5, 'BB Lips', 'assets/img/treatments/bb-lips.jpeg', 1);

INSERT INTO tratamiento_imagenes (id_tratamiento, titulo, ruta_archivo, orden_visual) VALUES
(6, 'Mesobótox', 'assets/img/treatments/mesobotox.jpeg', 1);

INSERT INTO tratamiento_parametros (id_tratamiento, nombre_parametro, valor_parametro, unidad) VALUES
(1, 'Duración del efecto', '2 a 4', 'meses');

INSERT INTO tratamiento_parametros (id_tratamiento, nombre_parametro, valor_parametro, unidad) VALUES
(1, 'Sesión', '1', 'aplicación');

INSERT INTO tratamiento_parametros (id_tratamiento, nombre_parametro, valor_parametro, unidad) VALUES
(2, 'Duración de sesión', '45', 'minutos');

INSERT INTO tratamiento_parametros (id_tratamiento, nombre_parametro, valor_parametro, unidad) VALUES
(3, 'Duración de sesión', '60', 'minutos');

INSERT INTO tratamiento_parametros (id_tratamiento, nombre_parametro, valor_parametro, unidad) VALUES
(4, 'Duración de sesión', '50', 'minutos');

INSERT INTO citas (id_paciente, id_tratamiento, fecha_hora, estado, motivo, notas) VALUES
(1, 2, TO_TIMESTAMP('2026-03-20 10:00:00','YYYY-MM-DD HH24:MI:SS'), 'SOLICITADA', 'Valoración inicial', 'Cita de prueba cargada desde el script SQL.');

INSERT INTO mensajes_contacto (nombre, email, telefono, asunto, mensaje) VALUES
('Ana Vargas', 'ana@gmail.com', '8888-1111', 'Consulta de botox', 'Conocer disponibilidad.');

INSERT INTO comentarios_tratamientos (id_tratamiento, id_paciente, calificacion, comentario) VALUES
(1, 1, 5, 'Muy buena orientación previa y seguimiento posterior.');
